# VARIABLES DEFINED IN `http-client.private.env.json` for ease of use.
# GET TOKEN BY USING `Helpers/Identity.Api/token` or `Identity.http` file.

### CREATE MOVIE
POST {{host}}/{{movies}}
Content-Type: application/json
Authorization: Bearer {{trustedToken}}

{
  "title": "Avengers: Endgame",
  "yearOfRelease": "2019",
  "genres": [
    "Action"
  ]
}


### GET MOVIES
GET {{host}}/{{movies}}
Content-Type: application/json
Authorization: Bearer {{userToken}}

### GET MOVIES
GET {{host}}/{{movies}}?title=b&yearOfRelease=1995
Content-Type: application/json
#Authorization: Bearer {{userToken}}




### GET MOVIE - ID
< {% request.variables.set("idOrSlug", "6e06f3cc-7932-41bd-9d87-8b7d19ce1356") %}

GET {{host}}/{{movies}}/{{idOrSlug}}
Content-Type: application/json
Authorization: Bearer {{userToken}}


### GET MOVIE - SLUG
< {% request.variables.set("idOrSlug", "avengers-endgame-2019") %}

GET {{host}}/{{movies}}/{{idOrSlug}}
Content-Type: application/json
Authorization: Bearer {{userToken}}


### UPDATE MOVIE
< {% request.variables.set("id", "6e06f3cc-7932-41bd-9d87-8b7d19ce1356") %}

PUT {{host}}/{{movies}}/{{id}}
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "title": "Avengers: Endgame",
  "yearOfRelease": "2019",
  "genres": [
    "Action",
    "Adventure",
    "Sci-Fi"
  ]
}


### DELETE MOVIE
< {% request.variables.set("id", "6e06f3cc-7932-41bd-9d87-8b7d19ce1356") %}

DELETE {{host}}/{{movies}}/{{id}}
Content-Type: application/json
Authorization: Bearer {{userToken}}

