### CREATE MOVIE
POST http://localhost:5072/api/movies
Content-Type: application/json

{
  "title": "Matrix 4",
  "yearOfRelease": "1921",
  "genres": [
    "Action"
  ]
}


### GET MOVIES
GET http://localhost:5072/api/movies
Content-Type: application/json


### GET MOVIE
< {% request.variables.set("idOrSlug", "matrix-4-1921") %}

GET http://localhost:5072/api/movies/{{idOrSlug}}
Content-Type: application/json


### UPDATE MOVIE
< {% request.variables.set("id", "8b94dc64-d3fe-4e86-8c67-5ef97ba8a8e9") %}

PUT http://localhost:5072/api/movies/{{id}}
Content-Type: application/json

{
  "title": "The Matrix 4",
  "yearOfRelease": "2021",
  "genres": [
    "Action",
    "Sci-Fi",
    "Thriller"
  ]
}


### DELETE MOVIE
< {% request.variables.set("id", "8b94dc64-d3fe-4e86-8c67-5ef97ba8a8e9") %}

DELETE http://localhost:5072/api/movies/{{id}}
Content-Type: application/json

